project: collectd_sds

targets:
  - SailfishOS-4.0.1.48-i486
  - SailfishOS-4.0.1.48-aarch64

rpms: RPMS

buildoptions: -j4

macros:
  - sailfishos 4.0

provides:
  spec/flatpak.spec:
     - pkgconfig(flatpak)
  spec/ostree.spec:
     - pkgconfig(ostree-1)
  spec/libappstream-glib.spec:
     - pkgconfig(appstream-glib)

insource:
  - spec/libappstream-glib.spec
